### ISSUE TITLE
Function to_rkm() for resistors returns incorrect values

### ISSUE THREAD

**Issue by fallanck** [KenKundert/rkm_codes#1]
Hello,
when I try to use  **to_rkm(Quantity(value, 'Ohm')** function, when value is  470, 47, 4.7 or 0.47 then the returned values are 470, 47, 4r7 and 470m.
The right values should be 470r, 47r, 4r7 (so this one is OK) and r470 according to https://en.wikipedia.org/wiki/RKM_code page, "Examples of resistance values" table.
I am using the set_prefs(rkm_maps=IEC60062_MAPS).

**Comment by KenKundert** [comment]
Of the 4 cases you mentioned, first consider the first two. It was my preference to strip off the extraneous R to make the code shorter. However it would be a simple matter to add another option that would disable this feature, and I'd be okay with making 470r be the default behavior. Does that work for you?

Now for the last value, 470m or r470. If we are supporting the small scale factors, then this is ambiguous. Both 470m and r470 represent the same value, but which should be preferred? It becomes more clear as the value gets smaller, so 47m seems better than r047, 4m7 seems better than r0047, and 470u seems better than r00047. However, it should be possible to specify that you do not want to use small scale factors. One way to do this would be to use the *output_sf* preference in Quantiphy.  Consider the following code:
```
>>> from quantiphy import Quantity
>>> from rkm_codes import from_rkm, to_rkm, set_prefs, IEC60062_MAPS, UNITLESS_MAPS

>>> set_prefs(
...     rkm_maps=IEC60062_MAPS, units_to_rkm_base_code={'Ω': 'R'}, map_sf=None,
...     show_units=None, strip_zeros=None, minus_sign=None, prec=4
... )

>>> q = Quantity('0.47uΩ')
>>> q.output_sf = 'TGMk'
>>> while q < 1e6:
...     vals = [
...         q,
...         to_rkm(q, strip_code=True),
...         to_rkm(q, strip_code=False),
...         to_rkm(q, show_units=True),
...         to_rkm(q, strip_zeros=False)
...     ]
...     values = ['  {:<9}'.format(v) for v in vals]
...     print(*values)
...     q = q.scale(10)
  470e-9 Ω    0           0R          0Ω          R0000
  4.7e-6 Ω    0           0R          0Ω          R0000
  47e-6 Ω     0           0R          0Ω          R0000
  470e-6 Ω    R0005       R0005       Ω0005       R0005
  4.7e-3 Ω    R0047       R0047       Ω0047       R0047
  47e-3 Ω     R047        R047        Ω047        R0470
  470e-3 Ω    R47         R47         Ω47         R4700
  4.7 Ω       4R7         4R7         4Ω7         4R7000
  47 Ω        47          47R         47Ω         47R000
  470 Ω       470         470R        470Ω        47R00
  4.7 kΩ      4K7         4K7         4KΩ7        4K7000
  47 kΩ       47K         47K         47KΩ        47K000
  470 kΩ      470K        470K        470KΩ       47K00
```
Here the scale factors are limited to TGMk, so m is not value and not used.  The current code does not support this, but I have implemented a version that does. So if this seems like it is a good approach, I will commit it.

**Comment by fallanck** [comment]
The proposed solutions are all right for me, thank you.
The new behavior would be more suitable for electronic component markings (my use case for your library).

**Comment by KenKundert** [comment]
Okay, give me a couple of days.

**Comment by KenKundert** [comment]
I have updated Github to version 0.4.2. Give it a try and let me know whether it works for you.
