### ISSUE TITLE
function to_rkm returns unusual formatted values

### ISSUE THREAD

**Issue by kleks85** [KenKundert/rkm_codes#2]
Hi,
when i try to use the to_rkm function i got unusual formatted return values.
The input from a list ['1.0R', '1.2R'] results in ['1d0e27', '1d2e27'].

Here is my short test code for this behaviour:

```python
from rkm_codes import to_rkm

precision = 1

list = ['1.0R', '1.2R', '1.5R', '1.8R', '2.2R', '2.7R', '3.3R', '3.9R', '4.7R', '5.6R', '6.8R', '8.2R', '10.0R', '12.0R', '15.0R', '18.0R', '22.0R', '27.0R', '33.0R', '39.0R', '47.0R', '56.0R', '68.0R', '82.0R', '100.0R', '120.0R', '150.0R', '180.0R', '220.0R', '270.0R', '330.0R', '390.0R', '470.0R', '560.0R', '680.0R', '820.0R', '1000.0R', '1200.0R', '1500.0R', '1800.0R', '2200.0R', '2700.0R', '3300.0R', 
'3900.0R', '4700.0R', '5600.0R', '6800.0R', '8200.0R', '10000.0R']

print(list)

for i in range(len(list)):
    list[i] = to_rkm(
        list[i], prec=precision, strip_code=False
        )
    
print(list)
```

**Comment by KenKundert** [comment]
Whoops.  I recently added the new SI scale factors to QuantiPhy (QRrq), and so R was being treated as a scale factor.  As such, '1.0R' was interpreted by QuantiPhy as 1e27.  I have suppressed rkm_code's use of the new scale factors, so things should be back to normal.  Can you check out the github version and try it out?  If so, let me know if you find any further issues.  If not, let me know and I will publish it to pypi.

**Comment by kleks85** [comment]
Hello,

i've tested your updated version "rkm_codes-0.5.1" and it is working again. Thank you very much for your quick response and have a nice weekend!

**Comment by KenKundert** [comment]
I have released the latest version on pypi.
